/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Player {
	/**
	 * プレイヤーの名前
	 */
	name: string[];
	/**
	 * レース人数
	 */
	racer: number;
	[k: string]: unknown;
}
